UniversityManagementSystem/UniversityManagementSystem/Controllers/EnrollCoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Models;
using Vereyon.Web;
using System.Data.Entity.Migrations;

namespace UniversityManagementSystem.Controllers
{
    public class EnrollCoursesController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: EnrollCourses
        public async Task<ActionResult> Index()
        {
            var enrollCourses = db.EnrollCourses.Include(e => e.Course).Include(e => e.Student);
            return View(await enrollCourses.ToListAsync());
        }

        

        // GET: EnrollCourses/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");
            return View();
        }

        // POST: EnrollCourses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EnrollCourseId,StudentId,CourseId,Date,GradeLetter,IsEnroll")] EnrollCourse enrollCourse)
        {
            if (ModelState.IsValid)
            {
                if (IsEnrolled(enrollCourse))
                {
                    FlashMessage.Danger("This Course is Already Enrolled");
                    return RedirectToAction("Create");
                }

                db.EnrollCourses.Add(enrollCourse);
                await db.SaveChangesAsync();
                FlashMessage.Confirmation("Course Enrolled Successfully");
                return RedirectToAction("Create");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", enrollCourse.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo", enrollCourse.StudentId);
            return View(enrollCourse);
        }

        public ActionResult SaveResult()
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "GradeLetter");
            return View();
        }

        [HttpPost]
        public ActionResult SaveResult([Bind(Include = "EnrollCourseId,StudentId,CourseId,Date,GradeLetter,IsEnroll")] EnrollCourse enrollCourse, FormCollection form)
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.GradeId = new SelectList(db.Grades, "GradeId", "GradeLetter");
            
            var enrollCourses = db.EnrollCourses.Where(s => s.StudentId == enrollCourse.StudentId && s.CourseId == enrollCourse.CourseId).ToList();

            int noOfEnrolledCourses = enrollCourses.Count();
            if (noOfEnrolledCourses == 1)
            {
                if(IsGraded(enrollCourse))
                {
                    FlashMessage.Danger("Already Graded");
                    return RedirectToAction("SaveResult");
                }

                var id = enrollCourses[0].EnrollCourseId;
                var sid = enrollCourses[0].StudentId;
                var cid = enrollCourses[0].CourseId;
                var date = enrollCourses[0].Date;
                //var grade = form["GradeId"].ToString(); //its working
                var grade = form["gradeLetter"].ToString(); //its working finallyyyyyyyyyy

                enrollCourse.EnrollCourseId = id;
                enrollCourse.StudentId = sid;
                enrollCourse.CourseId = cid;
                enrollCourse.Date = date;
                enrollCourse.GradeLetter = grade; //its working

                enrollCourse.IsGraded = true;
                db.EnrollCourses.AddOrUpdate(enrollCourse);
            }

            db.SaveChanges();
            FlashMessage.Confirmation("Result Saved Successfully");
            return View(enrollCourse);
        }

        public bool IsGraded(EnrollCourse enroll)
        {
            //var enrolledCourses = db.EnrollCourses.ToList();
            var enrolledCourse = db.EnrollCourses.Where(s => s.StudentId == enroll.StudentId && s.CourseId == enroll.CourseId).ToList();

            if (enrolledCourse.Any(c => (c.StudentId == enroll.StudentId) && (c.CourseId == enroll.CourseId) && (c.GradeLetter != null)))
            {
                return true;
            }
            return false;
        }


        public bool IsEnrolled(EnrollCourse enroll)
        {
            var enrolledCourses = db.EnrollCourses.ToList();

            if (enrolledCourses.Any(c => (c.CourseId == enroll.CourseId) && (c.StudentId == enroll.StudentId)))
            {
                return true;
            }

            return false;
        }

        

        public JsonResult GetStudentByStudentId(int studentId)
        {
            var student = db.Students.FirstOrDefault(s => s.StudentId == studentId);
            return Json(student);
        }

        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            var courses = db.Courses.Where(c => c.DepartmentId == departmentId).ToList();
            return Json(courses);
        }

        public JsonResult GetEnrolledCoursesByStudentId(int studentId)
        {
            var courses = db.EnrollCourses.Where(e => e.StudentId == studentId).ToList();
            return Json(courses);
        }


        public ActionResult ViewResult()
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "RegNo");
            return View();
        }

        public ActionResult GenerateResultReport()
        {
            var report = new Rotativa.ActionAsPdf("Index");
            return report;
        }



        // GET: EnrollCourses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnrollCourse enrollCourse = await db.EnrollCourses.FindAsync(id);
            if (enrollCourse == null)
            {
                return HttpNotFound();
            }
            return View(enrollCourse);
        }

        // POST: EnrollCourses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            EnrollCourse enrollCourse = await db.EnrollCourses.FindAsync(id);
            db.EnrollCourses.Remove(enrollCourse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Views/EnrollCourses/Create.cshtml
@model UniversityManagementSystem.Models.EnrollCourse
@using Vereyon.Web;

@{
    ViewBag.Title = "Course enrollment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Enroll In a Course</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.RenderFlashMessages()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Student Reg No.", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, "--Select Student--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Select Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, "--Select Course--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="Submit" value="Enroll" class="btn btn-success" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#Date").datepicker({
                dateFormat: "yy/mm/dd",
                changeMonth: true,
                changeYear: true
                //onSelect:
            }).datepicker("setDate", "today");

            $("#StudentId").change(function () {
                var id = $("#StudentId").val();
                var parameter = { studentId: id }
                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentByStudentId", "EnrollCourses")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (student) {
                        $("#StudentName").val(student.StudentName);
                        $("#Email").val(student.Email);
                        $("#Department").val(student.Department.DepartmentName);

                        //Course dropdown//
                        var deptId = student.Department.DepartmentId;
                        var param = { departmentId: deptId };
                        $("#CourseId").empty();
                        $("#CourseId").append('<option value=0>--Select Course--</option>');

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetCoursesByDepartmentId", "EnrollCourses")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(param),
                            success: function (courses) {
                                $.each(courses, function (key, value) {
                                    $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                                });
                            }
                        });
                    }
                });
            });
            //document ready
        });
    </script>
}

UniversityManagementSystem/UniversityManagementSystem/Views/EnrollCourses/Delete.cshtml
@model UniversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnrollCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradeLetter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradeLetter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsEnroll)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEnroll)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManagementSystem/UniversityManagementSystem/Views/EnrollCourses/Index.cshtml
@model IEnumerable<UniversityManagementSystem.Models.EnrollCourse>

@{
    ViewBag.Title = "Enrolled courses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Enrolled Courses</h2>
<hr />

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GradeLetter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Student.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GradeLetter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.EnrollCourseId })
        </td>
    </tr>
}

</table>

UniversityManagementSystem/UniversityManagementSystem/Views/EnrollCourses/SaveResult.cshtml
@model UniversityManagementSystem.Models.EnrollCourse
@using Vereyon.Web;

@{
    ViewBag.Title = "Save Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Save Result</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.RenderFlashMessages()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Student Reg No.", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, "--Select Student--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Select Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, "--Select Course--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Grade Letter", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradeId", null, "--Select Grade--", htmlAttributes: new { @class = "form-control" })

                <input type="hidden" id="gradeLetter" name="gradeLetter" value=""/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="Submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {

            $("#StudentId").change(function () {
                var id = $("#StudentId").val();
                var parameter = { studentId: id }

                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentByStudentId", "EnrollCourses")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (student) {
                        $("#StudentName").val(student.StudentName);
                        $("#Email").val(student.Email);
                        $("#Department").val(student.Department.DepartmentName);

                        //Course dropdown//
                        var stuId = $("#StudentId").val();
                        var param = { studentId: stuId };

                        $("#CourseId").empty();
                        $("#CourseId").append('<option value=0>--Select Course--</option>');

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetEnrolledCoursesByStudentId", "EnrollCourses")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(param),
                            success: function (courses) {
                                $.each(courses, function (key, value) {
                                    $("#CourseId").append('<option value=' + value.CourseId + '>' + value.Course.CourseCode + '</option>');
                                });
                            }
                        });
                    }
                });

                $("#GradeId").change(function () {
                    var grade = $("#GradeId option:selected").text();
                    $("#gradeLetter").val(grade);
                })

            });
            
            //ready end
        });
    </script>
}

UniversityManagementSystem/UniversityManagementSystem/Views/EnrollCourses/ViewResult.cshtml
@model UniversityManagementSystem.Models.EnrollCourse

@{
    ViewBag.Title = "View result of the student";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Result</h2>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Select Student Reg No.", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, "--Select Reg No--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" onclick="location.href='@Url.Action("GenerateResultReport", "EnrollCourses")'" value="Make PDF [Rotativa]" class="btn btn-success" />
                <input type="button" value="Make PDF [RDLC]" class="btn btn-primary" />
                @*<button type="button" onclick="location.href='@Url.Action("ReseultReport", "Results")'" class="btn btn-success" formaction="">Make PDF</button>*@
            </div>
        </div>

        <table class="table table-bordered table-striped" id="resultTable">
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Name</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody id="result"></tbody>
        </table>

    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#StudentId").change(function () {
                var id = $("#StudentId").val();
                var parameter = { studentId: id }

                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentByStudentId", "EnrollCourses")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (student) {
                        $("#StudentName").val(student.StudentName);
                        $("#Email").val(student.Email);
                        $("#Department").val(student.Department.DepartmentName);

                        //Course dropdown//

                        var stuId = $("#StudentId").val();
                        var param = { studentId: stuId };

                        $("#CourseId").empty();
                        $("#CourseId").append('<option value=0>--Select Course--</option>');
                        $("#result").empty();

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetEnrolledCoursesByStudentId", "EnrollCourses")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(param),
                            success: function (courses) {
                                $.each(courses, function (key, value) {
                                    $("#CourseId").append('<option value=' + value.Course.CourseId + '>' + value.Course.CourseCode + '</option>');

                                    var grade = value.GradeLetter;
                                    if (grade == null) {
                                        grade = 'Not Graded Yet';
                                    }

                                    $("#result").append(
                                        '<tr>' +
                                        '<td>' + value.Course.CourseCode + '</td>' +
                                        '<td>' + value.Course.CourseName + '</td>' +
                                        '<td>' + grade + '</td>' +
                                        '</tr>'
                                    )
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}