UniversityManagementSystem/UniversityManagementSystem/Controllers/AssignCoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Models;
using System.Data.Entity.Migrations;
using Vereyon.Web;

namespace UniversityManagementSystem.Controllers
{
    public class AssignCoursesController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: AssignCourses
        public async Task<ActionResult> Index()
        {
            var assignCourses = db.AssignCourses.Include(a => a.Course).Include(a => a.Department).Include(a => a.Teacher);
            return View(await assignCourses.ToListAsync());
        }


        // GET: AssignCourses/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode");
            //ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName");
            //ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");

            return View();
        }

        // POST: AssignCourses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AssignCourseId,DepartmentId,TeacherId,CreditToBeTaken,RemainingCredit,CourseId")] AssignCourse assignCourse)
        {
            if (ModelState.IsValid)
            {
                if (IsAssigned(assignCourse))
                {
                    FlashMessage.Danger("This Course is Already Assigned!");
                    return RedirectToAction("Create");
                }

                //assignCourse.Course.IsAssigned = true;

                db.AssignCourses.Add(assignCourse);
                await db.SaveChangesAsync();
                FlashMessage.Confirmation("Successfully Assigned");
                return RedirectToAction("Create");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode", assignCourse.DepartmentId);
            //ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName", assignCourse.TeacherId);
            //ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", assignCourse.CourseId);

            return View(assignCourse);
        }

        public bool IsAssigned(AssignCourse assign)
        {
            var assignedCourses = db.AssignCourses.ToList();

            if (assignedCourses.Any(c => (c.CourseId == assign.CourseId)))
            {
                return true;
            }
            return false;
        }


        //public JsonResult IsAssigned(int courseId)
        //{
        //    var assignedCourses = db.AssignCourses.ToList();

        //    if(assignedCourses.Any(c => c.AssignCourseId == courseId))
        //    {
        //        return Json(false, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        return Json(true, JsonRequestBehavior.AllowGet);
        //    }
        //} 



        public JsonResult GetTeachersByDeptId(int deptId)
        {
            var teachers = db.Teachers.Where(t => t.DepartmentId == deptId).ToList();
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByDeptId(int deptId)
        {
            var courses = db.Courses.Where(c => c.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeachersById(int teacherId)
        {
            Teacher teacher = db.Teachers.FirstOrDefault(t => t.TeacherId == teacherId);
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseById(int courseId)
        {
            Course course = db.Courses.FirstOrDefault(c => c.CourseId == courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveAssignCourse(AssignCourse assignCourse)
        {
            var asignCourseList = db.AssignCourses.Where(t => t.CourseId == assignCourse.CourseId && t.Course.IsAssigned == true).ToList();

            if (asignCourseList.Count > 0)
            {
                return Json(false);
            }

            else
            {
                db.AssignCourses.Add(assignCourse);
                db.SaveChanges();


                var teacher = db.Teachers.FirstOrDefault(t => t.TeacherId == assignCourse.TeacherId);
                if (teacher != null)
                {
                    teacher.RemainingCredit = assignCourse.RemainingCredit;
                    //teacher.RemainingCredit = teacher.CreditToBeTaken;

                    db.Teachers.AddOrUpdate(teacher);
                    db.SaveChanges();

                    var course = db.Courses.FirstOrDefault(c => c.CourseId == assignCourse.CourseId);
                    if (course != null)
                    {
                        course.IsAssigned = true;
                        course.AssignedTo = teacher.TeacherName;
                        db.Courses.AddOrUpdate(course);
                        db.SaveChanges();
                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }
                }
                return Json(false);
            }
        }


        public ActionResult ViewCourseStatistics()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName");
            return View();
        }
        public ActionResult GetCourseStatisticsByDeptId(int deptId)
        {
            var courses = db.Courses.Where(c => c.DepartmentId == deptId).ToList();
            return Json(courses);
        }


        public JsonResult UnAssignAllCourses(bool status)
        {
            var courses = db.Courses.Where(c => c.IsAssigned == true).ToList();
            var enrollCourses = db.EnrollCourses.Where(s => s.IsGraded == true).ToList();
            var teachers = db.AssignCourses.ToList();

            if (courses.Count == 0 && enrollCourses.Count == 0)
            {
                return Json(false);
            }
            else
            {
                foreach (var course in courses)
                {
                    course.IsAssigned = false;
                    course.AssignedTo = "NULL";
                    db.Courses.AddOrUpdate(course);
                    db.SaveChanges();
                }

                foreach (var enrollCourse in enrollCourses)
                {
                    enrollCourse.GradeLetter = null;
                    enrollCourse.IsGraded = false;
                    db.EnrollCourses.AddOrUpdate(enrollCourse);
                    db.SaveChanges();

                }
                foreach (var teacher in teachers)
                {
                    teacher.RemainingCredit = teacher.CreditToBeTaken;
                    teacher.Teacher.RemainingCredit = teacher.CreditToBeTaken;
                    db.AssignCourses.AddOrUpdate(teacher);
                    db.Teachers.AddOrUpdate(teacher.Teacher);
                    db.SaveChanges();
                }

                return Json(true);
            }
        }


        // GET: AssignCourses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssignCourse assignCourse = await db.AssignCourses.FindAsync(id);
            if (assignCourse == null)
            {
                return HttpNotFound();
            }
            return View(assignCourse);
        }

        // POST: AssignCourses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AssignCourse assignCourse = await db.AssignCourses.FindAsync(id);
            db.AssignCourses.Remove(assignCourse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Views/AssignCourses/Create.cshtml
@model UniversityManagementSystem.Models.AssignCourse
@using Vereyon.Web;

@{
    ViewBag.Title = "Assign course";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Assign Course to Teacher</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.RenderFlashMessages()

<div class="form-horizontal">
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentId", null, "--Select Department--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeacherId, "Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="TeacherId" name="TeacherId">
                <option>--Select Teacher--</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreditToBeTaken, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreditToBeTaken, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RemainingCredit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RemainingCredit, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    @*<div class="form-group">
        @Html.Label("Credit To Be Taken", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("CreditToBeTaken", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Remaining Credit", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("RemainingCredit", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Course Code", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="CourseId" name="CourseId">
                <option>--Select Course--</option>
            </select>
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourseCredit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CourseCredit, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="Submit" value="Assign" class="btn btn-success" />
            <input type="button" id="UnAssign" value="Unassign Courses" class="btn btn-danger" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {

                var deptId = $("#DepartmentId").val();
                var parameter = { deptId : deptId }

                $("#CreditToBeTaken").val("");
                $("#RemainingCredit").val("");
                $("#CourseName").val("");
                $("#CourseCredit").val("");

                $("#TeacherId").empty();
                $("#TeacherId").append('<option>--Select Teacher--</option>');

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeachersByDeptId", "AssignCourses")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (teacherList) {
                        $.each(teacherList, function (key, value) {
                            $("#TeacherId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                        });
                    }
                });

                $("#CourseId").empty();
                $("#CourseId").append('<option>--Select Course--</option>');

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByDeptId", "AssignCourses")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (courseList) {
                        $.each(courseList, function (key, value) {
                            $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                        });
                    }
                });
            });


            //Teacher Readonly
            $("#TeacherId").change(function () {
                var teacherId = $("#TeacherId").val();
                var jsnFormatData = { teacherId: teacherId };

                $("#CreditToBeTaken").val("");
                $("#RemainingCredit").val("");
                $("#CourseName").val("");
                $("#CourseCredit").val("");


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeachersById", "AssignCourses")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsnFormatData),
                    dataType: "json",
                    success: function(data) {
                        $("#CreditToBeTaken").val(data.CreditToBeTaken);
                        $("#RemainingCredit").val(data.RemainingCredit);
                        //$("#RemainingCredit").val(data.CreditToBeTaken - data.CourseCredit);
                    }
                });
            });


            //Course Readonly
            $("#CourseId").change(function() {
                var courseId = $("#CourseId").val();
                var jsnFormatData = { courseId: courseId };

                $("#CourseName").val("");
                $("#CourseCredit").val("");

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseById", "AssignCourses")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsnFormatData),
                    dataType: "json",
                    success: function(data) {
                        $("#CourseName").val(data.CourseName);
                        $("#CourseCredit").val(data.CourseCredit);
                    }
                });
            });

            //Un Assign Classrooms
            $("#UnAssign").click(function () {

                var flag = confirm("Are You Sure to Unassign All Courses?");
                if (flag == true) {
                    var jsonData = { status: flag };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("UnAssignAllCourses", "AssignCourses")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsonData),
                        dataType: "json",
                        success: function (data) {

                            if (data == true) {
                                alert("All Courses Unassigned Successffully!");
                            }
                            else
                            {
                                alert("No Courses Available to Unassgn");
                            }
                        }
                    });

                }
                return false;
            });


            //Assign Classrooms
            $("#Submit").click(function () {
                var departmentId = $("#DepartmentId").val();
                var teacherId = $("#TeacherId").val();
                var courseId = $("#CourseId").val();

                //var remain = parseFloat($("#RemainingCredit").val());
                //var credit = parseFloat($("#CourseCredit").val());
                //var remainingCredit = remain - credit;

                var remainingCredit = $("#RemainingCredit").val() - $("#CourseCredit").val();


                var flag = false;
                if (remainingCredit < 0) {
                    var flag = confirm("The Teacher's current credit is " + remainingCredit + " -Do You Want to Assign More ? ");
                    //if (flag == false) {
                    //    return false;
                    //}
                    //return true;
                }

                if (flag == true || remainingCredit > 0 || remainingCredit == 0) {
                    var takenCredit = $("#CreditToBeTaken").val();

                    var jsonData = { DepartmentId: departmentId, TeacherId: teacherId, CourseId: courseId, CreditToBeTaken: takenCredit, RemainingCredit: remainingCredit };


                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("SaveAssignCourse", "AssignCourses")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsonData),
                        dataType: "json",
                        success: function (data) {

                            if (data == true)
                                alert("Successfully Assigned");

                            else {
                                alert("Course is already Assigned");
                                return false;
                            }

                            $("#DepartmentId").val("");

                            $("#TeacherId").val("");
                            $("#CreditToBeTaken").val("");
                            $("#RemainingCredit").val("");

                            $("#CourseId").val("");
                            $("#CourseName").val("");
                            $("#CourseCredit").val("");
                            }
                        });
                    }
                return false;
            });
            return false;


        });
    </script>
}

UniversityManagementSystem/UniversityManagementSystem/Views/AssignCourses/Delete.cshtml
@model UniversityManagementSystem.Models.AssignCourse

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AssignCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.TeacherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditToBeTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditToBeTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainingCredit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainingCredit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManagementSystem/UniversityManagementSystem/Views/AssignCourses/Index.cshtml
@model IEnumerable<UniversityManagementSystem.Models.AssignCourse>

@{
    ViewBag.Title = "Assigned courses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Assigned Courses</h2>

 
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepartmentCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreditToBeTaken)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RemainingCredit)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.DepartmentCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teacher.TeacherName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreditToBeTaken)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RemainingCredit)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.AssignCourseId })
        </td>
    </tr>
}

</table>

UniversityManagementSystem/UniversityManagementSystem/Views/AssignCourses/ViewCourseStatistics.cshtml
@model UniversityManagementSystem.Models.AssignCourse


@{
    ViewBag.Title = "Course Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Course Statistics</h2>


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, "--Select Department--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <table class="table table-bordered table-striped" id="resultTable">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Name/Title</th>
                    <th>Semester</th>
                    <th>Assigned To</th>
                </tr>
            </thead>
            <tbody id="courseStat"></tbody>
        </table>

    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {
                var id = $("#DepartmentId").val();
                var parameter = { deptId: id }
                $("#courseStat").empty();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseStatisticsByDeptId", "AssignCourses")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(parameter),
                    success: function (courses) {
                        $.each(courses, function (key, value) {

                            var teacher = value.AssignedTo;
                            if (teacher == null) {
                                teacher = 'Not Assigned Yet';
                            }

                            $("#courseStat").append(
                                '<tr>' +
                                '<td>' + value.CourseCode + '</td>' +
                                '<td>' + value.CourseName + '</td>' +
                                '<td>' + value.Semester.SemesterNo + '</td>' +
                                '<td>' + teacher + '</td>' +
                                '</tr>'
                            )
                         });
                    }
                });
            });
        });
    </script>
}