UniversityManagementSystem/UniversityManagementSystem/Models/AllocatedClassroom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UniversityManagementSystem.Models
{
    public class AllocatedClassroom
    {
        [Key]
        public int AllocatedClassroomId { get; set; }

        [Display(Name = "Department")]
        [Required(ErrorMessage = "Please Select Department")]
        public int DepartmentId { get; set; }
        [ForeignKey("DepartmentId")]
        public virtual Department Department { get; set; }

        [Display(Name = "Course")]
        [Required(ErrorMessage = "Please Select Course")]
        public int CourseId { get; set; }
        public virtual Course Course { get; set; }

        [Display(Name = "Room")]
        [Required(ErrorMessage = "Please Select Room")]
        public int RoomId { get; set; }
        [ForeignKey("RoomId")]
        public virtual Room Room { get; set; }

        [Display(Name = "Day")]
        [Required(ErrorMessage = "Please Select Day")]
        public int DayId { get; set; }
        [ForeignKey("DayId")]
        public virtual Day Day { get; set; }

        [Required(ErrorMessage ="Please Enter Starting Time")]
        [Display(Name = "From")]
        //[Column(TypeName ="time")]
        //[DataType(DataType.Time)]
        public string FromTime { get; set; }

        [Required(ErrorMessage = "Please Enter Finishing Time")]
        [Display(Name = "To")]
        //[Column(TypeName="time")]
        //[DataType(DataType.Time)]
        public string ToTime { get; set; }

        public bool IsAllocated { get; set; }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/AllocatedClassroomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.Models;
using Vereyon.Web;
using System.Data.Entity.Migrations;

namespace UniversityManagementSystem.Controllers
{
    public class AllocatedClassroomsController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: AllocatedClassrooms
        public async Task<ActionResult> Index()
        {
            var allocatedClassroms = db.AllocatedClassroms.Include(a => a.Course).Include(a => a.Day).Include(a => a.Department).Include(a => a.Room);
            return View(await allocatedClassroms.ToListAsync());
        }

        

        // GET: AllocatedClassrooms/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.DayId = new SelectList(db.Days, "DayId", "DayName");
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomNo");
            return View();
        }

        // POST: AllocatedClassrooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AllocatedClassroomId,DepartmentId,CourseId,RoomId,DayId,FromTime,ToTime,AllocationStatus")] AllocatedClassroom allocatedClassroom)
        {
            if (ModelState.IsValid)
            {
                allocatedClassroom.IsAllocated = true;

                db.AllocatedClassroms.Add(allocatedClassroom);
                await db.SaveChangesAsync();
                FlashMessage.Confirmation("Room Successfully Allocated");
                return RedirectToAction("Create");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", allocatedClassroom.CourseId);
            ViewBag.DayId = new SelectList(db.Days, "DayId", "DayName", allocatedClassroom.DayId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode", allocatedClassroom.DepartmentId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomNo", allocatedClassroom.RoomId);
            return View(allocatedClassroom);
        }

        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            var courses = db.Courses.Where(c => c.DepartmentId == departmentId).ToList();
            return Json(courses);
        }


        public JsonResult UnallocateAllRooms(bool status)
        {
            var allocatedClassrooms = db.AllocatedClassroms.Where(r => r.IsAllocated == true).ToList();
            if (allocatedClassrooms.Count == 0)
            {
                return Json(false);
            }
            else
            {
                foreach (var room in allocatedClassrooms)
                {
                    room.IsAllocated = false;
                    db.AllocatedClassroms.AddOrUpdate(room);
                    db.SaveChanges();
                }
                return Json(true);
            }
        }

        // GET: AllocatedClassrooms/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AllocatedClassroom allocatedClassroom = await db.AllocatedClassroms.FindAsync(id);
            if (allocatedClassroom == null)
            {
                return HttpNotFound();
            }
            return View(allocatedClassroom);
        }

        // POST: AllocatedClassrooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AllocatedClassroom allocatedClassroom = await db.AllocatedClassroms.FindAsync(id);
            db.AllocatedClassroms.Remove(allocatedClassroom);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Views/AllocatedClassrooms/Create.cshtml
@model UniversityManagementSystem.Models.AllocatedClassroom
@using Vereyon.Web

@{
    ViewBag.Title = "Allocate classroom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Allocate Classroom</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.RenderFlashMessages()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, "--Select Department--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="CourseId" name="CourseId">
                    <option>--Select Course--</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "Room", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, "--Select Room--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayId, "Day", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayId", null, "--Select Day--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromTime, "From", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToTime, "To", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToTime, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="Submit" value="Allocate" class="btn btn-success" />
                <input type="button" value="Unallocate Rooms" id="Unallocate" class="btn btn-danger" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">


    <script>
        $(document).ready(function () {

            $("#DepartmentId").change(function () {
                var deptId = $("#DepartmentId").val();
                var parameter = { departmentId: deptId }
                $("#CourseId").empty();
                $("#CourseId").append('<option>--Select Course--</option>');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByDepartmentId", "AllocatedClassrooms")',
                    contentType: "application/json; charset= utf-8",
                    data: JSON.stringify(parameter),
                    success: function (courseList) {
                        $.each(courseList, function (key, value) {
                            $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseName + '</option>');
                        });
                    }
                });
            });

            $('#FromTime').timepicker({
                timeFormat: 'h:mm p',
                interval: 30,
                minTime: '8:30am',
                maxTime: '4:00pm',
                defaultTime: '8:30am',
                startTime: '8:30',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });

            $('#ToTime').timepicker({
                timeFormat: 'h:mm p',
                interval: 30,
                minTime: '10:00am',
                maxTime: '5:30pm',
                defaultTime: '10:00am',
                startTime: '10:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });


            $("#Submit").click(function () {
                var departmentId = $("#DepartmentId").val();
                var courseId = $("#CourseId").val();
                var roomId = $("#RoomId").val();
                var dayId = $("#DayId").val();

                var time = $("#FromTime").val();
                var hour = parseInt(time.substr(0, 2));
                var minute = parseInt(time.substr(3, 5));
                var fromTime = hour * 60 + minute;
                //alert(hour);
                //alert(minute);
                //alert(fromTime);

                var time = $("#ToTime").val();
                hour = parseInt(time.substr(0, 2));
                minute = parseInt(time.substr(3, 5));
                var toTime = hour * 60 + minute;
                //alert(hour);
                //alert(minute);
                //alert(toTime);

                if (fromTime == toTime) {
                    alert("A class can not Start and End at the same time");
                    return false;
                }

            });


            $("#Unallocate").click(function () {
                var flag = confirm("Are You Sure to Unallocate All Classrooms Schedule?");

                if (flag == true) {
                    var jsonData = { status: flag };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("UnallocateAllRooms", "AllocatedClassrooms")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsonData),
                        dataType: "json",
                        success: function (data) {
                            if (data == true) {
                                alert("All Rooms Unallocated Successffully!");
                            }
                            else {
                                alert("No Rooms Available to Unallocate");
                            }
                        }
                    });

                }
                return false;
            });


        });
    </script>
}

UniversityManagementSystem/UniversityManagementSystem/Views/AllocatedClassrooms/Delete.cshtml
@model UniversityManagementSystem.Models.AllocatedClassroom

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AllocatedClassroom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day.DayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day.DayName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllocationStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllocationStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManagementSystem/UniversityManagementSystem/Views/AllocatedClassrooms/Index.cshtml
@model IEnumerable<UniversityManagementSystem.Models.AllocatedClassroom>

@{
    ViewBag.Title = "Allocated classrooms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Allocated Classrooms</h2>
<hr />

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.Label("Course Code")
        </th>
        <th>
            @Html.Label("Department")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Day.DayName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Room.RoomNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.DepartmentCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day.DayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Room.RoomNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToTime)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.AllocatedClassroomId })
        </td>
    </tr>
}

</table>